### ISSUE TITLE
Extension has been broken.

### ISSUE THREAD

**Issue by Kimobonbon** [brycebostwick/FixTheGulf#3]
Sorry to break it to you, but google already broke your extension. For me it just says "Gulf of Mexico (Gulf of America)" instead of just "Gulf of Mexico". I'm so sad this is broken, because it's really cool. Your content is great, by the way.

**Comment by Demohstens** [comment]
Seems to work fine for me :)
Try clearing your cache.
It displays "Gulf of Mexico (Gulf of Mexico)" internationally as google shows both names outside of the US. 
A pull Request has been submitted to fix this, though!

**Comment by brycebostwick** [comment]
If clearing cache doesn't work for you, would love more info here, esp Browser / Browser Version. I suspect Google Maps might have multiple ways to send this tile data down (I've seen in the past where they've sent pre-rendered tiles with label data on top, though not sure if that's completely gone — but I wonder if there are either some environments or some A/B test where that still happens)

**Comment by cranberry3148** [comment]
It seems like the function signature of _.id has changed. For me it's
```
'function(a,b,c,d,e){c=c[Symbol.iterator]();let {done:f,value:g}=c.next();if(f)_.lc(a,b);else{a=_.dd(a,b);for(b=0;!f;{done:f,value:g}=c.next())a[b++]=d(g);a.length=b;e&&Hfa(a)}}'
```

**Comment by FlamedDogo99** [comment]
It no longer replaces the canvas name for me either.

**Comment by cobaltjacket** [comment]
On Edge or 133.0.3065.59 (Windows) or 133.0.3065.69 (Windows) or Chrome 133.0.6945.0 (Windows), it does not seem to work - on my work systems.

On my personal systems (Edge 133.0.3065.69 - Windows, Edge 132..0.2957.115 (Mac), it works fine. I suspect there is an issue with admx controls inhibiting the plugin. This is not the end of the world, but I just thought I'd remark on it.

**Comment by brycebostwick** [comment]
> It seems like the function signature of _.id has changed. For me it's
> 
> ```
> 'function(a,b,c,d,e){c=c[Symbol.iterator]();let {done:f,value:g}=c.next();if(f)_.lc(a,b);else{a=_.dd(a,b);for(b=0;!f;{done:f,value:g}=c.next())a[b++]=d(g);a.length=b;e&&Hfa(a)}}'
> ```

I think this should be fine/expected - the names of all these functions change essentially any time Google pushes out a maps update (which I assume is pretty frequently). This is what [`findFunction`](https://github.com/brycebostwick/FixTheGulf/blob/b40ed628a0d4b2e7d150d33c46cfe5b8272b2a7a/gulf.js#L42) is supposed to solve. Running this in the console:

```js
const findFunction = (stringRepresentation) => {
    return Object.keys(_).find(key => _[key] && _[key].toString && _[key].toString() === stringRepresentation)
}

findFunction('function(a,b){const c=JSON.parse(a);if(Array.isArray(c))return new b(c);throw Error("U`"+a);}')
```

Gives me `jd` right now rather than `id`. The script should handle that part OK!

**Comment by brycebostwick** [comment]
That being said, I have found at least two issues now when trying to test this on Firefox (I don't assume they're Firefox's fault / I'm sure they could happen elsewhere) -

1) This `findFunction` implementation calls `.toString()` on a bunch of random objects in the hopes of finding the function we're looking for. It looks like on some objects, that `toString()` call can throw an error - this makes the whole `findFunction` call fail, and we don't find/patch the correct function accordingly.

```
Uncaught TypeError: this.Xe is undefined
    getUTCFullYear (...)loadSv.O:;:1175
    eE (...)loadSv.O:;:1179
    eE (...)loadSv.O:;:1182
    toString (...)loadSv.O:;:1182
    findFunction <anonymous code>:7
    findFunction <anonymous code>:5
    <anonymous> <anonymous code>:18
    <anonymous> <anonymous code>:137
```

I think that can be easily fixed by just wrapping each `toString()` call in a try/catch so that if one fails, we still continue on.

2) I'm seeing a race condition in which the plugin runs, but Google's scripts haven't run yet; this means the `findFunction` call fails, but if I manually run it again later, then it succeeds.

Right now the plugin is relying on manifest.json's `"run_at": "document_idle"` to run after everything else has already downloaded, but seems like that's probably not sufficient. Having a way to run the plugin script only _after_ the other scripts have run should fix that. It looks like there might be a couple good ways to do that, but if anyone with more experience here already knows a nice pattern there, let me know!

**Comment by JM117** [comment]
Interestingly, the extension does seem to work when logged out, but stops working when logged in. This happens even in an Incognito session, so it shouldn't have anything to do with cookies/cache data.

**Comment by TogiFerretFerret** [comment]
Still doesn't work when logged in - Hopefully will be patched soon.

**Comment by bobjoerules** [comment]
Doesn't work still 

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/9da5030b-6260-449b-8df1-b32a3957c91d" />
